const CLEVER_INSULTS = [
  "Você é como uma atualização de software inútil: ocupa espaço e não resolve nada.",
  "Sua lógica é tão confusa que até o Google se perde.",
  "Você tem tanta originalidade quanto um relatório de reunião semanal.",
  "Conversar com você é como tentar ensinar física quântica a uma pedra.",
  "Sua presença é como pop-ups: ninguém pediu, mas todos sofrem.",
  "Você fala tanto e diz tão pouco que é quase arte moderna.",
  "Sua memória é como cache de navegador: sempre cheia e sem utilidade.",
  "Você tem tanto senso de timing quanto um relógio quebrado.",
  "Você é o tipo de pessoa que coloca a chave do carro dentro do carro e ainda acha que é esperto.",
  "Sua argumentação é tão sólida quanto uma nuvem.",
  "Você brilha tanto quanto uma lâmpada queimada.",
  "Você tem tanto charme quanto uma segunda-feira chuvosa.",
  "Conversar com você é como tentar extrair sentido de um meme ruim.",
  "Sua criatividade é como papelão molhado: inútil e sem forma.",
  "Você tenta ser profundo, mas é só raso demais para notar.",
  "Você é como manual de instrução em chinês: ninguém entende nada.",
  "Sua capacidade de argumentar é inversamente proporcional à sua teimosia.",
  "Você tem o talento de transformar simplicidade em complicação.",
  "Sua sagacidade é tão afiada quanto uma colher de plástico.",
  "Você é como um software antigo: lento, cheio de bugs e ninguém usa.",
  "Sua intuição é tão confiável quanto previsão do tempo em dia de tempestade.",
  "Conversar com você é um exercício de paciência olímpica.",
  "Você tenta ser moderno, mas sua mente está em 1999.",
  "Sua coerência é como areia: impossível de segurar.",
  "Você tem a originalidade de um meme reciclado.",
  "Sua lógica é tão linear quanto uma curva.",
  "Você é como tutorial sem imagens: ninguém consegue acompanhar.",
  "Sua conversa é como spam: irritante e repetitiva.",
  "Você se esforça para impressionar, mas só consegue confundir.",
  "Sua capacidade de improviso é tão boa quanto um script sem depuração.",
  "Você é como luz apagada: ninguém nota sua presença.",
  "Sua memória é tão confiável quanto papel molhado.",
  "Você tenta parecer interessante, mas é só entediante mesmo.",
  "Sua sagacidade é como sopa sem tempero: insossa e esquecível.",
  "Você é como tutorial em PDF: longo, cansativo e ninguém lê até o fim.",
  "Sua criatividade é como água parada: sem movimento, sem propósito.",
  "Conversar com você é como tentar abrir uma porta trancada sem a chave.",
  "Você é como aplicativo mal programado: trava em qualquer situação.",
  "Sua capacidade de observação é menor que uma formiga míope.",
  "Você tenta ser espirituoso, mas só consegue ser previsível.",
  "Sua argumentação é tão frágil quanto castelo de cartas em vento forte.",
  "Você é como Wi-Fi instável: conecta, desconecta e ninguém aguenta.",
  "Sua lógica é tão complexa quanto receita de miojo.",
  "Você é a prova viva de que nem tudo que existe é útil.",
  "Sua memória é tão boa quanto buraco negro: engole tudo e não devolve nada.",
  "Sua sagacidade é tão afiada quanto colher de pau.",
  "Você é como um tutorial em loop infinito: não leva a lugar nenhum.",
  "Sua capacidade de síntese é inversamente proporcional à sua verbosidade.",
  "Você é como software obsoleto: ninguém quer atualizar.",
  "Sua habilidade de resolver problemas é como Internet discada: lenta e frustrante.",
  "Sua conversa é como propaganda invasiva: ninguém presta atenção.",
  "Você é como luz de LED quebrada: piscando e sem sentido.",
  "Sua lógica é tão coerente quanto uma nota de rodapé perdida.",
  "Você tenta ser engenhoso, mas é só previsível mesmo.",
  "Sua capacidade de reflexão é tão curta quanto café frio.",
  "Você é como vídeo sem legenda: difícil de entender e chato.",
  "Sua sagacidade é como piada sem punchline: inútil.",
  "Sua presença é como notificação inútil: ninguém quer.",
  "Você é como um teste sem respostas: frustrante e confuso.",
  "Sua inteligência estratégica é equivalente à de uma galinha perdendo um grão.",
  "Sua astúcia é equiparável à de uma chaleira fervendo sem água.",
  "Seu discernimento rivaliza com o de um boneco de cera.",
  "Você demonstra raciocínio crítico como um saco de batatas.",
  "Sua perícia em argumentação é como uma vela na tempestade.",
  "Você possui a graça de uma tartaruga em patins.",
  "Seu intelecto é equiparável a um livro sem páginas.",
  "Você possui a agudeza de uma caneta sem tinta.",
  "Sua retórica é tão afiada quanto algodão.",
  "Você apresenta ideias com a elegância de uma porta rangendo.",
  "Sua sagacidade rivaliza com um pote vazio.",
  "Você possui a profundidade de uma poça de água.",
  "Seu senso de humor é comparável a uma parede lisa.",
  "Você expressa genialidade como um sino quebrado.",
  "Sua astúcia é equiparável à de uma pedra plana.",
  "Você possui a sutileza de um martelo pneumático.",
  "Sua argumentação é tão sólida quanto fumaça.",
  "Você demonstra perspicácia como uma pedra no caminho.",
  "Seu discernimento rivaliza com uma nuvem em dia nublado.",
  "Você possui a agudeza de um travesseiro de penas.",
  "Sua eloquência se compara a um tambor silencioso.",
  "Você apresenta lógica como areia soprada pelo vento.",
  "Sua inteligência estratégica é equivalente à de um lustre desligado.",
  "Você comunica ideias com a clareza de uma janela suja.",
  "Sua finesse rivaliza com a de uma porta de armário emperrada.",
  "Você possui a agilidade mental de um carvalho secular.",
  "Sua argúcia é tão evidente quanto tinta invisível.",
  "Você demonstra raciocínio crítico como um relógio sem ponteiros.",
  "Sua perícia em raciocínio é comparável a um livro queimado.",
  "Você possui a profundidade de uma folha caída.",
  "Seu intelecto rivaliza com uma vela apagada.",
  "Você comunica ideias com a perspicácia de um tijolo.",
  "Sua lógica é tão clara quanto lama turva.",
  "Você demonstra sagacidade como uma porta trancada sem chave.",
  "Sua inteligência estratégica é comparável a uma cadeira quebrada.",
  "Você possui a elegância de um guarda-chuva aberto em dia de tempestade.",
  "Sua retórica rivaliza com a de um eco distante.",
  "Você expressa ideias com a sutileza de um trovão na sala.",
  "Sua astúcia é tão evidente quanto fumaça de brasa apagada.",
  "Sua sabedoria é proporcional à velocidade de uma tartaruga em férias.",
  "Você tem a perspicácia de um tijolo muito bem polido.",
  "Sua eloquência é digna de um manual de micro-ondas.",
  "Você raciocina com a agilidade de um caracol filosofando.",
  "Sua sutileza rivaliza com um rinoceronte numa loja de cristais.",
  "Você expressa ideias com a clareza de uma neblina espessa.",
  "Sua lógica é tão firme quanto gelatina dançando.",
  "Você demonstra astúcia como um guarda-chuva virado pelo vento.",
  "Seu senso crítico é equivalente a uma porta fechada sem maçaneta.",
  "Você comunica pensamentos com a delicadeza de um trovão em sala de aula.",
  "Sua argumentação é tão sólida quanto fumaça em tempestade.",
  "Você possui a criatividade de uma pedra contemplando o nada.",
  "Seu intelecto é como uma vela acesa na chuva: iluminado mas inútil.",
  "Você tem a perspicácia de um relógio sem ponteiros.",
  "Sua eloquência é tão impressionante quanto uma poça d’água.",
  "Você demonstra raciocínio crítico como uma porta de armário emperrada.",
  "Sua sagacidade é comparável a um carrinho de supermercado sem rodas.",
  "Você possui a profundidade de um pires de chá.",
  "Seu charme é equivalente ao de um bloco de concreto.",
  "Você comunica ideias com a clareza de uma janela suja de lama.",
  "Sua capacidade de improviso é como um caracol participando de corrida olímpica.",
  "Você demonstra lógica como areia soprada pelo vento.",
  "Sua inteligência estratégica é como uma cadeira quebrada.",
  "Você possui a elegância de um guarda-chuva aberto em dia de tempestade.",
  "Sua retórica rivaliza com o eco de uma sala vazia.",
  "Você expressa ideias com a sutileza de um trovão na sala de aula.",
  "Sua astúcia é tão evidente quanto tinta invisível.",
  "Você comunica pensamentos como um sino quebrado: faz barulho mas ninguém entende.",
  "Sua perspicácia rivaliza com a de um balde vazio.",
  "Você demonstra raciocínio crítico como uma planta de plástico: aparenta, mas não produz.",
  "Sua lógica é tão confiável quanto previsão do tempo em dia de tempestade.",
  "Você possui a criatividade de um tutorial de como respirar.",
  "Seu intelecto é tão vasto quanto uma poça de água no deserto.",
  "Você expressa ideias com a clareza de um vídeo sem legenda.",
  "Sua sagacidade rivaliza com a de uma colher de pau.",
  "Você possui a profundidade de um prato raso.",
  "Sua capacidade de síntese é tão grande quanto um elefante numa caixa de sapatos.",
  "Você comunica pensamentos com a elegância de uma porta rangendo.",
  "Sua inteligência é como uma lâmpada apagada: existe, mas ninguém nota.",
  "Você demonstra raciocínio crítico como um sapo assistindo TV.",
  "Sua astúcia é comparável à de um gato contemplando o vazio.",
  "Você possui a perspicácia de um coelho perdido na floresta.",
  "Sua retórica é tão envolvente quanto uma parede lisa.",
  "Você expressa genialidade como uma vela apagada.",
  "Sua lógica rivaliza com um castelo de cartas em vento forte.",
  "Você comunica ideias com a sofisticação de uma torradeira.",
  "Sua inteligência estratégica é como uma escada sem degraus.",
  "Você demonstra raciocínio crítico como um bloco de concreto.",
  "Sua sagacidade rivaliza com a de um pires vazio.",
  "Você possui a originalidade de um meme reciclado.",
  "Sua capacidade de improviso é equivalente a uma tartaruga em patins.",
  "Você expressa pensamentos com a delicadeza de uma bomba de confete."
];


export function get_one_clever_insult(){
    const index = Math.floor(Math.random() * CLEVER_INSULTS.length)
    return CLEVER_INSULTS[index]
}
