const PICKUP_LINES = [
  "Você acredita em amor à primeira vista ou devo passar por aqui mais uma vez?" ,
  "Desculpe, mas você tem um mapa? Porque eu me perdi nos seus olhos." ,
  "Se beleza fosse tempo, você seria a eternidade." ,
  "Você deve ser um mágico, porque sempre que olho para você, tudo ao meu redor desaparece." ,
  "Eu não sou fotógrafo, mas consigo nos imaginar juntos em várias fotos." ,
  "Se eu fosse um gato, passaria todas as minhas vidas ao seu lado." ,
  "Você é como um aplicativo para o meu coração, porque eu não consigo parar de pensar em você." ,
  "Desculpe, mas você é tão linda que me fez esquecer a cantada que ia te contar." ,
  "Você é a razão pela qual eu olho para o meu celular em plena rua." ,
  "Se eu pudesse rearranjar o alfabeto, colocaria V e C juntos de mim.",
  "Se você fosse um sonho, eu nunca iria querer acordar.",
  "Você é uma estrela? Porque seu brilho ilumina meu dia.",
    "Você não é Wi-Fi, mas sinto uma conexão incrível.",
  "Se beleza fosse crime, você estaria presa eternamente.",
  "Você deve ser feita de açúcar, porque adoça meu dia.",
  "Meu coração tem um bug: só funciona quando você está por perto.",
  "Se eu fosse um poeta, escreveria sua presença em cada verso.",
  "Você não é mapa, mas me faz perder o rumo.",
  "Se sorrisos fossem moedas, você seria milionária.",
  "Você é tão incrível que até o sol se esconde pra te admirar.",
  "Se estrelas caíssem cada vez que penso em você, o céu já estaria vazio.",
  "Você não é café, mas me deixa acordado o dia todo pensando em você.",
  "Se meus olhos fossem câmeras, você estaria em todas as fotos.",
  "Você é a notificação que eu sempre quero receber.",
  "Se o amor fosse ciência, você seria a fórmula perfeita.",
  "Você não é música, mas meu coração bate no seu ritmo.",
  "Se o tempo parasse quando nos olhamos, eu nem me importaria.",
  "Você é como o sol, ilumina tudo ao redor.",
  "Se beijos fossem raios, eu te enviaria um sol inteiro.",
  "Você não é arte, mas me inspira de um jeito único.",
  "Se você fosse um aplicativo, eu faria download sem pensar.",
  "Você é a razão de todos os meus sorrisos inesperados.",
  "Se eu fosse um livro, cada página teria seu nome.",
  "Você não é tempestade, mas faz meu coração acelerar.",
  "Se palavras pudessem voar, eu enviaria mil só pra você.",
  "Você é o motivo do meu coração bater mais rápido.",
  "Se eu fosse música, você seria minha melodia favorita.",
  "Você não é estrela, mas ilumina meu céu particular.",
  "Se eu tivesse um desejo, seria te fazer sorrir todos os dias.",
  "Você é a página mais bonita do meu diário.",
  "Se fosse pintura, eu te penduraria no melhor lugar da galeria.",
  "Você não é lua, mas faz meu mundo brilhar à noite.",
  "Se eu pudesse te dar uma estrela, seria a mais brilhante.",
  "Você é o café que faltava pra completar minha manhã.",
  "Se eu fosse poeta, você seria meu verso eterno.",
  "Você não é livro, mas quero ler você todos os dias.",
  "Se meus olhos falassem, eles só diriam seu nome.",
  "Você é o código que faltava pro meu coração funcionar.",
  "Se eu fosse rei, você seria meu tesouro.",
  "Você não é feitiço, mas me deixa encantado.",
  "Se eu fosse viagem, meu destino seria você.",
  "Você é o sol depois da chuva nos meus dias nublados.",
  "Se eu pudesse desenhar felicidade, você seria meu traço favorito.",
  "Você não é remédio, mas cura qualquer tristeza minha.",
  "Se meus dias fossem páginas, você seria o capítulo principal.",
  "Você é o emoji que falta nas minhas mensagens.",
  "Se eu fosse jogo, você seria meu objetivo final.",
  "Você não é poema, mas rima com tudo que é bom na vida.",
  "Se eu tivesse asas, voaria só pra te ver sorrir.",
  "Você é a notificação que sempre quero receber.",
  "Se eu fosse aplicativo, você estaria sempre aberto no meu coração.",
  "Você não é planeta, mas gira tudo ao meu redor.",
  "Se eu pudesse escolher, ficaria só no seu mundo.",
  "Você é o sol que aquece meus dias frios.",
  "Se eu fosse música, você seria minha nota favorita.",
  "Você não é luz, mas ilumina meu caminho inteiro.",
  "Se eu fosse quadro, você seria minha obra-prima.",
  "Você é o sorriso que me faz esquecer qualquer problema.",
  "Se eu pudesse viajar, só iria onde você estiver.",
  "Você não é vento, mas me leva pra lugares incríveis.",
  "Se eu fosse letra, você seria minha canção.",
  "Você é o motivo de todos os meus sorrisos.",
  "Se eu fosse onda, só iria até você.",
  "Você não é céu, mas faz meu mundo infinito.",
  "Se eu fosse chuva, só cairia sobre você.",
  "Você é o brilho que falta nos meus dias.",
  "Se eu pudesse escolher uma estrela, seria você.",
  "Você não é fogo, mas aquece meu coração.",
  "Se eu fosse café, você seria meu despertar.",
  "Você é a luz que guia meu caminho.",
  "Se eu fosse caminho, te levaria até meu coração.",
  "Você não é flor, mas perfuma minha vida inteira.",
  "Se eu fosse céu, você seria meu pôr do sol favorito.",
  "Você é o motivo de eu acreditar no amor.",
  "Se eu pudesse escrever, só escreveria você.",
  "Você não é magia, mas me deixa encantado.",
  "Se eu fosse rio, só correria pra você.",
  "Você é o abraço que eu nunca quero soltar.",
  "Se eu fosse estrela, brilharia só pra você.",
  "Você não é perfume, mas deixa tudo mais doce.",
  "Se eu fosse estrada, só iria te encontrar.",
  "Você é o sorriso que transforma meu dia.",
  "Se eu fosse vento, só sopraria pra você.",
  "Você não é sol, mas aquece meus dias frios.",
  "Se eu fosse fogo, só queimaria por você.",
  "Você é o destino que eu sempre quis encontrar.",
  "Se eu pudesse voar, seria só pra te ver.",
  "Você não é melodia, mas faz meu coração dançar.",
  "Se eu fosse lua, só iluminaria você.",
  "Você é a razão do meu melhor sorriso.",
  "Se eu fosse poema, só teria você como verso.",
  "Você não é arco-íris, mas colore meu mundo.",
  "Se eu fosse perfume, só cheiraria a você.",
  "Você é a página mais bonita do meu livro.",
  "Se eu fosse estrela cadente, realizaria seu desejo.",
  "Você não é água, mas sacia minha sede de amor.",
  "Se eu fosse jardim, só floresceria por você.",
  "Você é a música que quero ouvir todos os dias.",
  "Se eu pudesse escolher um tesouro, seria você.",
  "Você não é tempo, mas faz meus segundos valerem a pena.",
  "Se eu fosse coração, só bateria por você.",
  "Você é a luz que ilumina meus melhores dias.",
  "Se eu fosse sonho, você seria minha realidade.",
  "Você não é vento, mas me leva pra lugares incríveis.",
  "Se eu fosse caminho, só seguiria até você.",
  "Você é o motivo do meu sorriso diário.",
  "Se eu fosse chuva, só molharia você.",
  "Você não é fogo, mas acende meu coração.",
  "Se eu fosse rio, só correria pra você.",
  "Você é a estrela que brilha mais no meu céu.",
  "Se eu fosse café, só despertaria pensando em você.",
  "Você não é poema, mas rima com tudo que é bom.",
  "Se eu fosse sol, só iluminaria você.",
  "Você é a melodia que meu coração quer ouvir.",
  "Se eu fosse quadro, você seria minha obra-prima.",
  "Você não é mapa, mas me faz perder o rumo.",
  "Se eu fosse vento, só sopraria pra você.",
  "Você é a razão de todos os meus sorrisos.",
  "Se eu fosse letra, você seria minha canção favorita.",
  "Você não é perfume, mas deixa tudo mais doce.",
  "Se eu fosse estrela, brilharia só por você.",
  "Você é o destino que eu sempre quis alcançar.",
  "Se eu fosse lua, só iluminaria você.",
  "Você não é fogo, mas aquece meu coração.",
  "Se eu fosse livro, só escreveria você.",
  "Você é a página mais bonita do meu diário.",
  "Se eu fosse música, você seria minha nota favorita."
]
export function get_one_pickup_line(){
    const index = Math.floor(Math.random() * PICKUP_LINES.length)
    return PICKUP_LINES[index]
}